Repository uchicago-library/library_website, pull requests merged in 2020-01, with the labels that each got.

#229 Unpublished news stories that are scheduled to be published appear on kiosk pages
  base/models.py
Labels: bug, fixed in dev, ready to merge

#231 Bad link on staff directory
  units/templates/units/unit_index_page.html
Labels: bug, fixed in dev

#233 Changed labeling of Scholarly Communication nav section
  base/templates/base/includes/header.html
Labels: ready to merge
