Repository uchicago-library/library_website, pull requests merged in 2020-04, with the labels that each got.

#279 Limited minute types to wagtail page and changed table styling
  base/templates/base/minutes_and_reports_inner_table.html
  group/models.py
Labels: question

#296 Subject dropdown display problem
  units/tests.py
  units/views.py
Labels: fixed in dev

#297 Library spaces page hours widget bug
  base/models.py
  public/templates/public/location_page.html
Labels: fixed in dev

#300 Improvements for the external include api
  base/templates/base/includes/css.html
  base/templates/base/includes/js.html
  base/views.py
  library_website/settings/base.py
Labels: bug, fixed in dev

#302 Add event tracking to links in reusable content boxes
  base/static/base/js/ga.public.js
Labels: enhancement, fixed in dev

#309 Fix Travis CI
  .travis.yml
  library_website/settings/base.py
  staff/utils.py
Labels: bug
