Repository uchicago-library/library_website, pull requests merged in 2020-03, with the labels that each got.

#265 Fixed broken link for the CDS page in main nav
  base/templates/base/includes/header.html
Labels: ready to merge

#268 Added alert link to Loop quicklinks
  base/static/base/css/loop/loop.scss
  intranethome/templates/intranethome/intranet_home_page.html
Labels: ready to merge

#272 Alert banners should display on browse views
  alerts/utils.py
  events/views.py
  lib_collections/views.py
  public/views.py
  units/views.py
Labels: bug, ready to merge

#274 Reverted changes that prevented needed page types under StandardPages
  public/models.py
Labels: ready to merge

#283 Commented out ILL links and enlarged ematerials text
  public/templates/public/blocks/search_widget.html
Labels: ready to merge

#286 Changed inline to inline-block in banner
  base/static/base/css/base.scss
  base/static/base/css/uclib.scss
  base/templates/base/public_base.html
Labels: enhancement
